quote_list = [
    "Be kind whenever possible. It is always possible."
    "Music - it's motivational and just makes you relax."
    "Sometimes I'll put on a Zig Ziglar tape: he's a motivational speaker who is really funny and really American. I know I should do the things he says, but I'm too cynical."
    "Many are called but few get up."
    "The way to get started is to quit talking and begin doing."
    "If you can dream it, you can do it."
    "Know or listen to those who know."
    "The wise does at once what the fool does at last."
    "You can't cross the sea merely by standing and staring at the water."
    "How do you know you're going to do something, untill you do it?"
    "Beginning today, treat everyone you meet as if they were going to be dead by midnight. Extend to them all the care, kindness and understanding you can muster, and do it with no thought of any reward. Your life will never be the same again."
    "Always do your best. What you plant now, you will harvest later."
    "Failure will never overtake me if my determination to succeed is strong enough."
    "We should not give up and we should not allow the problem to defeat us."
    "You just can't beat the person who never gives up."
    "You have to learn the rules of the game. And then you have to play better than anyone else."
    "The past cannot be changed. The future is yet in your power."
    "Deserve your dream."
    "Decide what you want, decide what you are willing to exchange for it. Establish your priorities and go to work."
    "I used to watch a lot of motivational films and videos to remain positive."
    "Aim for the moon. If you miss, you may hit a star."
    "You must take action now that will move you towards your goals. Develop a sense of urgency in your life."
    "If you fell down yesterday, stand up today."
    "Madam Walker was a master marketer. But her brilliance was in taking it to another level by training women, by traveling, by making very motivational speeches and by providing independent income for women who otherwise would have to be maids and sharecroppers."
    "Do not weep; do not wax indignant. Understand."
    "To be a good loser is to learn how to win."
    "Don't watch the clock; do what it does. Keep going."
    "When you fail you learn from the mistakes you made and it motivates you to work even harder."
    "I learned that we can do anything, but we can't do everything... at least not at the same time. So think of your priorities not in terms of what activities you do, but when you do them. Timing is everything."
    "Even if you fall on your face, you're still moving forward."
    "Go for it now. The future is promised to no one."
    "You can't wait for inspiration. You have to go after it with a club."
    "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice."
    "We make the world we live in and shape our own environment."
    "A will finds a way."
    "A goal is a dream with a deadline."
    "There is progress whether ye are going forward or backward! The thing is to move!"
    "Do the one thing you think you cannot do. Fail at it. Try again. Do better the second time. The only people who never tumble are those who never mount the high wire. This is your moment. Own it."
    "After my ski jumping career finished, I went back to school to study law, and now I travel between five to 20 times a year doing after-dinner speaking, motivational talks, appearances, openings, TV and radio shows."
    "Earl Nightingale has inspired more people toward success and fortune than any other motivational speaker on the planet."
    "What you get by achieving your goals is not as important as what you become by achieving your goals."
    "I'm a motivational speaker."
    "As long as I'm not selling out the people that ride or die with me, I'm glad I'm not an MC. I'm a motivational speaker. I'm not that rapper dude."
    "Do the difficult things while they are easy and do the great things while they are small. A journey of a thousand miles must begin with a single step."
    "Be gentle to all and stern with yourself."
    "Perseverance is not a long race; it is many short races one after the other."
    "I'm going to write a book, continue acting, continue motivational speaking and just share with people who I am and what I've learned in my second chance of life and pass it on to people in their first chance of life."
    "Ever since I was a kid, I knew I could play in the NFL because I had a knack for the game. But I can't play this game forever. When I'm finished, maybe I'll become a motivational speaker, maybe a preacher. But children need to know that life may be hard, but you can always overcome."
    "If you want to conquer fear, don't sit home and think about it. Go out and get busy."
]